import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.services": "Services",
    "nav.wallet": "Wallet",
    "nav.myProducts": "My Products",
    "nav.promote": "Promote",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.account": "Account",
    "nav.navigation": "Navigation",
    "nav.settings": "Settings",
    "nav.language": "Language",
    "nav.lightMode": "Light Mode",
    "nav.darkMode": "Dark Mode",
    
    // Dashboard/Home
    "home.title": "VIRO",
    "home.subtitle": "Iraq's Premier Digital Services Marketplace",
    "home.description": "Connect with verified sellers, discover quality services, and grow your digital business",
    "home.search.placeholder": "Search for services...",
    "home.search.button": "Search",
    "home.stats.activeServices": "Active Services",
    "home.stats.verifiedSellers": "Verified Sellers",
    "home.stats.totalSales": "Total Sales",
    "home.featuredServices": "Featured Services",
    "home.featuredServices.subtitle": "Top-rated services from verified sellers",
    "home.viewAll": "View All",
    "home.cta.title": "Ready to Start Selling?",
    "home.cta.description": "Join thousands of sellers on Iraq's fastest-growing digital marketplace",
    "home.cta.getStarted": "Get Started",
    "home.startingAt": "Starting at",
    "home.viewDetails": "View Details",
    
    // Services Page
    "services.title": "Discover Services",
    "services.subtitle": "Browse and find the perfect service for your needs",
    "services.searchPlaceholder": "Search services...",
    "services.filters": "Filters",
    "services.filterDescription": "Filter services by category and price",
    "services.category": "Category",
    "services.priceRange": "Price Range",
    "services.all": "all",
    "services.allCategories": "All Categories",
    "services.allPrices": "All Prices",
    "services.design": "Design",
    "services.development": "Development",
    "services.marketing": "Marketing",
    "services.writing": "Writing",
    "services.videoAnimation": "Video & Animation",
    "services.musicAudio": "Music & Audio",
    "services.under50": "Under $50",
    "services.50to100": "$50 - $100",
    "services.100to200": "$100 - $200",
    "services.over200": "Over $200",
    "services.clearFilters": "Clear Filters",
    "services.search": "Search",
    "services.categoryLabel": "Category",
    "services.priceLabel": "Price",
    "services.selectCategory": "Select category",
    "services.selectPriceRange": "Select price range",
    "services.buyNow": "Buy Now",
    "services.loginToBuy": "Login to Buy",
    "services.yourProduct": "Your Product",
    "services.loadMore": "Load More Services",
    "services.noResults": "No services found",
    "services.tryDifferent": "Try adjusting your filters",
    "services.purchaseSuccess": "Purchase Successful!",
    "services.purchasedProduct": "You have successfully purchased",
    "services.purchaseFailed": "Purchase Failed",
    "services.purchaseError": "Failed to complete purchase",
    "services.confirmPurchase": "Confirm Purchase",
    "services.reviewDetails": "Review your purchase details before confirming",
    "services.service": "Service",
    "services.seller": "Seller",
    "services.price": "Price",
    "services.yourBalance": "Your Balance",
    "services.balanceAfter": "Balance After Purchase",
    "services.cancel": "Cancel",
    "services.confirm": "Confirm Purchase",
    "services.processing": "Processing...",
    "services.insufficientBalance": "Your balance is insufficient to complete this purchase. Please deposit more funds to your wallet.",
    "services.accountCredentials": "Account Credentials",
    "services.credentialsDelivered": "Your account credentials have been delivered",
    "services.saveCredentials": "Please save these credentials securely",
    "services.categories.design": "Design",
    "services.categories.development": "Development",
    "services.categories.marketing": "Marketing",
    "services.categories.writing": "Writing",
    "services.categories.videoAnimation": "Video & Animation",
    "services.categories.musicAudio": "Music & Audio",
    "services.categories.instagram": "Instagram",
    "services.categories.tiktok": "TikTok",
    "services.categories.netflix": "Netflix",
    "services.categories.youtube": "YouTube",
    "services.categories.spotify": "Spotify",
    "services.categories.telegramNumbers": "Telegram Numbers",
    "services.categories.subscriptions": "Subscriptions",
    "services.categories.courses": "Courses",
    "services.categories.games": "Games",
    "services.instagram": "Instagram",
    "services.tiktok": "TikTok",
    "services.netflix": "Netflix",
    "services.youtube": "YouTube",
    "services.spotify": "Spotify",
    "services.telegramNumbers": "Telegram Numbers",
    "services.subscriptions": "Subscriptions",
    "services.notFound": "Service Not Found",
    "services.details": "Service Details",
    "services.views": "Views",
    "services.sales": "Sales",
    "services.rating": "Rating",
    "services.discount": "Save",
    "services.purchasing": "Processing...",
    "services.loginRequired": "Please login to purchase this service",
    "services.loginRequiredDescription": "You must be logged in to purchase services",
    "services.inactive": "Inactive",
    "services.purchaseSuccess.description": "Check your chats to communicate with the seller",
    
    // Common
    "common.back": "Back",
    "common.goHome": "Go Home",
    
    // Wallet
    "wallet.title": "My Wallet",
    "wallet.subtitle": "Manage your balance and transactions",
    "wallet.balance": "Current Balance",
    "wallet.totalEarnings": "Total Earnings",
    "wallet.deposit": "Deposit",
    "wallet.withdraw": "Withdraw",
    "wallet.transactions": "Transaction History",
    "wallet.transactionsSubtitle": "Your recent wallet activity",
    "wallet.noTransactions": "No transactions yet",
    "wallet.startUsing": "Start using your wallet to see transactions",
    "wallet.recentEarnings": "Recent Earnings",
    "wallet.last30Days": "Last 30 days",
    "wallet.thisMonth": "this month",
    "wallet.depositFunds": "Deposit Funds",
    "wallet.depositDescription": "Add money to your Viro wallet",
    "wallet.withdrawFunds": "Withdraw Funds",
    "wallet.withdrawDescription": "Withdraw money from your Viro wallet",
    "wallet.amount": "Amount (USD)",
    "wallet.amountPlaceholder": "0.00",
    "wallet.paymentMethod": "Payment Method",
    "wallet.withdrawTo": "Withdraw To",
    "wallet.selectMethod": "Select payment method",
    "wallet.selectWithdrawMethod": "Select withdrawal method",
    "wallet.depositSuccess": "Deposit Successful",
    "wallet.depositFailed": "Deposit Failed",
    "wallet.withdrawSuccess": "Withdrawal Successful",
    "wallet.withdrawFailed": "Withdrawal Failed",
    "wallet.addedToWallet": "has been added to your wallet",
    "wallet.withdrawnFrom": "has been withdrawn from your wallet",
    "wallet.depositError": "Could not complete deposit",
    "wallet.withdrawError": "Could not complete withdrawal",
    "wallet.confirmDeposit": "Confirm Deposit",
    "wallet.confirmWithdrawal": "Confirm Withdrawal",
    "wallet.processing": "Processing...",
    "wallet.viewAll": "View All Transactions",
    "wallet.noDescription": "No description",
    "wallet.zainCash": "Zain Cash",
    "wallet.alRafidain": "Al-Rafidain QiServices",
    "wallet.fib": "FIB",
    "wallet.platformZainNumber": "Platform Zain Cash Number",
    "wallet.transferToThisNumber": "Transfer the amount to this number",
    "wallet.yourWalletNumber": "Your Wallet Number",
    "wallet.enterWalletNumber": "Enter your wallet number used for transfer",
    "wallet.walletNumberHint": "Enter the wallet number you used to send the money",
    "wallet.platformRafidainAccount": "Platform Rafidain Account Number",
    "wallet.transferToThisAccount": "Transfer the amount to this bank account",
    "wallet.yourAccountNumber": "Your Account Number",
    "wallet.enterAccountNumber": "Enter your account number used for transfer",
    "wallet.accountNumberHint": "Enter the account number you used to send the money",
    "wallet.type": "Type",
    "wallet.status": "Status",
    "wallet.date": "Date",
    "wallet.sale": "Sale",
    "wallet.purchase": "Purchase",
    "wallet.promotion": "Promotion",
    "wallet.completed": "Completed",
    "wallet.pending": "Pending",
    "wallet.failed": "Failed",
    "wallet.feeNotice": "A fee will be deducted",
    "wallet.depositFeeNotice": "A processing fee will be applied to this deposit",
    "wallet.withdrawFeeNotice": "A processing fee will be applied to this withdrawal",
    "wallet.depositAmount": "Deposit Amount",
    "wallet.withdrawalAmount": "Withdrawal Amount",
    "wallet.processingFee": "Processing Fee (5%)",
    "wallet.youWillReceive": "You Will Receive",
    
    // Auth
      "auth.welcomeBack": "مرحباً بك مجدداً",
      "auth.createAccount": "إنشاء حساب",
      "auth.enterCredentials": "أدخل بياناتك للوصول إلى حسابك",
      "auth.joinTiro": "انضم إلى فيرو وابدأ بيع الخدمات الرقمية",
      "auth.fullName": "الاسم الكامل",
      "auth.email": "البريد الإلكتروني",
      "auth.username": "اسم المستخدم",
      "auth.password": "كلمة المرور",
    "auth.login": "Login",
    "auth.dontHaveAccount": "Don't have an account?",
    "auth.signUp": "Sign up",
    "auth.alreadyHaveAccount": "Already have an account?",
    "auth.loginSuccess": "Login successful!",
    "auth.welcomeTo": "Welcome back to Viro",
    "auth.accountCreated": "Account created!",
    "auth.welcomeToPlatform": "Welcome to Viro platform",
    
    // My Products
    "myProducts.title": "My Products",
    "myProducts.subtitle": "Manage your services and offerings",
    "myProducts.addNewService": "Add New Service",
    "myProducts.createService": "Create a new service to offer on Viro marketplace",
    "myProducts.serviceTitle": "Service Title",
    "myProducts.titlePlaceholder": "Professional Logo Design",
    "myProducts.description": "Description",
    "myProducts.descriptionPlaceholder": "Describe your service in detail...",
    "myProducts.priceUSD": "Price (USD)",
    "myProducts.pricePlaceholder": "50.00",
    "myProducts.category": "Category",
    "myProducts.selectCategory": "Select category",
    "myProducts.accountDetails": "Account Details",
    "myProducts.accountUsername": "Account Username",
    "myProducts.accountPassword": "Account Password",
    "myProducts.accountEmail": "Account Email",
    "myProducts.accountEmailPassword": "Email Password",
    "myProducts.subscriptionDuration": "Subscription Duration",
    "myProducts.selectDuration": "Select duration",
    "myProducts.1month": "1 Month",
    "myProducts.3months": "3 Months",
    "myProducts.6months": "6 Months",
    "myProducts.12months": "12 Months",
    "myProducts.netflixDetails": "Netflix Subscription Details",
    "myProducts.youtubeDetails": "YouTube Account Details",
    "myProducts.spotifyDetails": "Spotify Subscription Details",
    "myProducts.telegramNumbersDetails": "Telegram Number Details",
    "myProducts.subscriptionsDetails": "Subscription Account Details",
    "myProducts.subscriptionEmail": "Account Email",
    "myProducts.subscriptionCode": "Account Code / Password",
    "myProducts.telegramPhoneNumber": "Phone Number to Sell",
    "myProducts.telegramPhonePlaceholder": "",
    "myProducts.courseUrl": "رابط الكورس",
    "myProducts.courseUrlPlaceholder": "https://example.com/course",
    "myProducts.gameType": "اسم اللعبة",
    "myProducts.gameTypePlaceholder": "مثال: ببجي، فري فاير",
    "myProducts.usernamePlaceholder": "username123",
    "myProducts.passwordPlaceholder": "password",
    "myProducts.emailPlaceholder": "user@example.com",
    "myProducts.emailPasswordPlaceholder": "email password",
    "myProducts.saving": "Saving...",
    "myProducts.updateService": "Update Service",
    "myProducts.createServiceBtn": "Create Service",
    "myProducts.totalServices": "Total Services",
    "myProducts.totalViews": "Total Views",
    "myProducts.totalSales": "Total Sales",
    "myProducts.views": "views",
    "myProducts.sales": "sales",
    "myProducts.editService": "Edit Service",
    "myProducts.updateDetails": "Update your service details",
    "myProducts.deleteService": "Delete Service",
    "myProducts.deleteConfirm": "Are you sure you want to delete",
    "myProducts.deleteWarning": "This action cannot be undone.",
    "myProducts.deleting": "Deleting...",
    "myProducts.noProducts": "No services yet",
    "myProducts.noProductsDescription": "Create your first service to start selling on Viro",
    "myProducts.addFirstService": "Add Your First Service",
    "myProducts.active": "Active",
    "myProducts.inactive": "Inactive",
    "myProducts.createSuccess": "Service created successfully",
    "myProducts.updateSuccess": "Service updated successfully",
    "myProducts.deleteSuccess": "Service deleted successfully",
    "myProducts.verificationRequired": "Verification Required",
    "myProducts.verificationMessage": "Only verified sellers can publish services on Viro. Please apply for account verification to start selling your services.",
    "myProducts.applyForVerification": "Apply for Verification",
    
    // Promote
    "promote.title": "Promote Your Services",
    "promote.subtitle": "Boost your visibility and reach more customers with our promotion packages",
    "promote.premiumSpotlight": "Premium Spotlight",
    "promote.featuredPosition": "Featured Position",
    "promote.visibilityBoost": "Visibility Boost",
    "promote.top3Description": "Get maximum exposure with premium placement",
    "promote.top5Description": "Stand out with featured positioning",
    "promote.top10Description": "Get your service noticed",
    "promote.top3": "Top 3",
    "promote.top5": "Top 5",
    "promote.top10": "Top 10",
    "promote.perPromotion": "/promotion",
    "promote.selectPlan": "Select Plan",
    "promote.selectProduct": "Select Product",
    "promote.chooseProduct": "Choose a product to promote",
    "promote.selectPromote": "Select a product to promote with",
    "promote.package": "package",
    "promote.promotionSummary": "Promotion Summary",
    "promote.packageLabel": "Package",
    "promote.position": "Position",
    "promote.duration": "Duration",
    "promote.daysCount": "days",
    "promote.total": "Total",
    "promote.creating": "Creating...",
    "promote.startPromotion": "Start Promotion",
    "promote.activePromotions": "Active Promotions",
    "promote.activePromotionsDescription": "Your currently running promotion campaigns",
    "promote.active": "Active",
    "promote.day": "day",
    "promote.daysRemaining": "days remaining",
    "promote.noPromotions": "No active promotions",
    "promote.noPromotionsDescription": "Start promoting your services to increase visibility",
    "promote.activationSuccess": "Promotion Activated!",
    "promote.activationSuccessMessage": "Your promotion has been created and is now active.",
    "promote.activationFailed": "Promotion Failed",
    "promote.activationError": "Failed to create promotion",
    "promote.selectProductError": "Please select a product to promote",
    "promote.loginRequired": "You must be logged in to create a promotion",
    "promote.benefit1Top3": "Featured in top 3 products",
    "promote.benefit2Top3": "Maximum visibility",
    "promote.benefit3Top3": "Highlighted with gold badge",
    "promote.benefit4Top3": "3 days promotion",
    "promote.benefit5Top3": "Priority in search results",
    "promote.benefit1Top5": "Featured in top 5 products",
    "promote.benefit2Top5": "High visibility",
    "promote.benefit3Top5": "Featured badge",
    "promote.benefit4Top5": "2 days promotion",
    "promote.benefit5Top5": "Boosted in search",
    "promote.benefit1Top10": "Featured in top 10 products",
    "promote.benefit2Top10": "Good visibility",
    "promote.benefit3Top10": "Promoted badge",
    "promote.benefit4Top10": "1 day promotion",
    "promote.benefit5Top10": "Search ranking boost",
    
    // Profile
    "profile.title": "Profile",
    "profile.editProfile": "Edit Profile",
    "profile.save": "Save",
    "profile.saving": "Saving...",
    "profile.cancel": "Cancel",
    "profile.personalInfo": "Profile Information",
    "profile.personalInfoDescription": "Your personal details and bio",
    "profile.fullName": "Full Name",
    "profile.username": "Username",
    "profile.email": "Email",
    "profile.bio": "Bio",
    "profile.performanceStats": "Performance Stats",
    "profile.performanceDescription": "Your achievements on Viro",
    "profile.rating": "Rating",
    "profile.reviews": "reviews",
    "profile.totalSales": "Total Sales",
    "profile.sellerRank": "Seller Rank",
    "profile.top": "Top",
    "profile.accountStatus": "Account Status",
    "profile.verification": "Verification",
    "profile.verified": "Verified",
    "profile.notVerified": "Not Verified",
    "profile.memberSince": "Member Since",
    "profile.accountType": "Account Type",
    "profile.seller": "Seller",
    "profile.quickActions": "Quick Actions",
    "profile.changePassword": "Change Password",
    "profile.notificationSettings": "Notification Settings",
    
    // Not Found
    "notFound.title": "Page Not Found",
    "notFound.message": "The page you're looking for doesn't exist or has been moved",
    "notFound.goHome": "Go Home",
    "notFound.goBack": "Go Back",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
  },
  ar: {
    // Navigation
    "nav.dashboard": "لوحة التحكم",
    "nav.services": "الخدمات",
    "nav.wallet": "المحفظة",
    "nav.myProducts": "منتجاتي",
    "nav.promote": "الترويج",
    "nav.profile": "الملف الشخصي",
    "nav.logout": "تسجيل الخروج",
    "nav.login": "تسجيل الدخول",
    "nav.signup": "إنشاء حساب",
    "nav.account": "الحساب",
    "nav.navigation": "التنقل",
    "nav.settings": "الإعدادات",
    "nav.language": "اللغة",
    "nav.lightMode": "الوضع الفاتح",
    "nav.darkMode": "الوضع الداكن",
    
    // Dashboard/Home
    "home.title": "فيرو",
    "home.subtitle": "منصة العراق الرائدة للخدمات الرقمية",
    "home.description": "تواصل مع بائعين موثوقين، اكتشف خدمات عالية الجودة، وقم بتنمية عملك الرقمي",
    "home.search.placeholder": "ابحث عن الخدمات...",
    "home.search.button": "بحث",
    "home.stats.activeServices": "خدمات نشطة",
    "home.stats.verifiedSellers": "بائعين موثوقين",
    "home.stats.totalSales": "إجمالي المبيعات",
    "home.featuredServices": "الخدمات المميزة",
    "home.featuredServices.subtitle": "خدمات بتقييم عالي من بائعين موثوقين",
    "home.viewAll": "عرض الكل",
    "home.cta.title": "هل أنت مستعد لبدء البيع؟",
    "home.cta.description": "انضم إلى آلاف البائعين في أسرع سوق رقمي نمواً في العراق",
    "home.cta.getStarted": "ابدأ الآن",
    "home.startingAt": "يبدأ من",
    "home.viewDetails": "عرض التفاصيل",
    
    // Services Page
    "services.title": "اكتشف الخدمات",
    "services.subtitle": "تصفح وابحث عن الخدمة المثالية لاحتياجاتك",
    "services.searchPlaceholder": "ابحث عن الخدمات...",
    "services.filters": "التصفيات",
    "services.filterDescription": "صفي الخدمات حسب الفئة والسعر",
    "services.category": "الفئة",
    "services.priceRange": "نطاق السعر",
    "services.all": "الكل",
    "services.allCategories": "جميع الفئات",
    "services.allPrices": "جميع الأسعار",
    "services.design": "تصميم",
    "services.development": "تطوير",
    "services.marketing": "تسويق",
    "services.writing": "كتابة",
    "services.videoAnimation": "فيديو ورسوم متحركة",
    "services.musicAudio": "موسيقى وصوت",
    "services.under50": "أقل من 50$",
    "services.50to100": "50$ - 100$",
    "services.100to200": "100$ - 200$",
    "services.over200": "أكثر من 200$",
    "services.clearFilters": "مسح التصفيات",
    "services.search": "بحث",
    "services.categoryLabel": "الفئة",
    "services.priceLabel": "السعر",
    "services.selectCategory": "اختر الفئة",
    "services.selectPriceRange": "اختر نطاق السعر",
    "services.buyNow": "اشتر الآن",
    "services.loginToBuy": "سجل دخول للشراء",
    "services.yourProduct": "منتجك",
    "services.loadMore": "تحميل المزيد من الخدمات",
    "services.noResults": "لا توجد خدمات",
    "services.tryDifferent": "حاول تعديل التصفيات",
    "services.purchaseSuccess": "تمت العملية بنجاح!",
    "services.purchasedProduct": "لقد قمت بشراء",
    "services.purchaseFailed": "فشلت عملية الشراء",
    "services.purchaseError": "فشل إتمام عملية الشراء",
    "services.confirmPurchase": "تأكيد الشراء",
    "services.reviewDetails": "راجع تفاصيل الشراء قبل التأكيد",
    "services.service": "الخدمة",
    "services.seller": "البائع",
    "services.price": "السعر",
    "services.yourBalance": "رصيدك",
    "services.balanceAfter": "الرصيد بعد الشراء",
    "services.cancel": "إلغاء",
    "services.confirm": "تأكيد الشراء",
    "services.processing": "جاري المعالجة...",
    "services.insufficientBalance": "رصيدك غير كافٍ لإتمام هذا الشراء. يرجى إيداع المزيد من الأموال في محفظتك.",
    "services.accountCredentials": "بيانات الحساب",
    "services.credentialsDelivered": "تم تسليم بيانات الحساب",
    "services.saveCredentials": "يرجى حفظ هذه البيانات بشكل آمن",
    "services.categories.design": "تصميم",
    "services.categories.development": "برمجة",
    "services.categories.marketing": "تسويق",
    "services.categories.writing": "كتابة",
    "services.categories.videoAnimation": "فيديو وأنيميشن",
    "services.categories.musicAudio": "موسيقى وصوتيات",
    "services.categories.instagram": "إنستغرام",
    "services.categories.tiktok": "تيك توك",
    "services.categories.netflix": "نتفلكس",
    "services.categories.youtube": "يوتيوب",
    "services.categories.spotify": "سبوتفاي",
    "services.categories.telegramNumbers": "أرقام تليجرام",
    "services.categories.subscriptions": "اشتراكات",
    "services.categories.courses": "كورسات",
    "services.categories.games": "ألعاب",
    "services.instagram": "إنستغرام",
    "services.tiktok": "تيك توك",
    "services.netflix": "نتفلكس",
    "services.youtube": "يوتيوب",
    "services.spotify": "سبوتفاي",
    "services.telegramNumbers": "أرقام تليجرام",
    "services.subscriptions": "اشتراكات",
    "services.notFound": "الخدمة غير موجودة",
    "services.details": "تفاصيل الخدمة",
    "services.views": "المشاهدات",
    "services.sales": "المبيعات",
    "services.rating": "التقييم",
    "services.discount": "وفر",
    "services.purchasing": "جاري المعالجة...",
    "services.loginRequired": "يرجى تسجيل الدخول لشراء هذه الخدمة",
    "services.loginRequiredDescription": "يجب تسجيل الدخول لشراء الخدمات",
    "services.inactive": "غير نشط",
    "services.purchaseSuccess.description": "تحقق من المحادثات للتواصل مع البائع",
    
    // Common
    "common.back": "رجوع",
    "common.goHome": "العودة للرئيسية",
    
    // Wallet
    "wallet.title": "محفظتي",
    "wallet.subtitle": "إدارة رصيدك ومعاملاتك",
    "wallet.balance": "الرصيد الحالي",
    "wallet.totalEarnings": "إجمالي الأرباح",
    "wallet.deposit": "إيداع",
    "wallet.withdraw": "سحب",
    "wallet.transactions": "سجل المعاملات",
    "wallet.transactionsSubtitle": "نشاط محفظتك الأخير",
    "wallet.noTransactions": "لا توجد معاملات بعد",
    "wallet.startUsing": "ابدأ باستخدام محفظتك لرؤية المعاملات",
    "wallet.recentEarnings": "الأرباح الأخيرة",
    "wallet.last30Days": "آخر 30 يوماً",
    "wallet.thisMonth": "هذا الشهر",
    "wallet.depositFunds": "إيداع أموال",
    "wallet.depositDescription": "أضف أموال إلى محفظة تيرو",
    "wallet.withdrawFunds": "سحب أموال",
    "wallet.withdrawDescription": "اسحب أموال من محفظة تيرو",
    "wallet.amount": "المبلغ (دولار)",
    "wallet.amountPlaceholder": "0.00",
    "wallet.paymentMethod": "وسيلة الدفع",
    "wallet.withdrawTo": "السحب إلى",
    "wallet.selectMethod": "اختر وسيلة الدفع",
    "wallet.selectWithdrawMethod": "اختر وسيلة السحب",
    "wallet.depositSuccess": "تم الإيداع بنجاح",
    "wallet.depositFailed": "فشل الإيداع",
    "wallet.withdrawSuccess": "تم السحب بنجاح",
    "wallet.withdrawFailed": "فشل السحب",
    "wallet.addedToWallet": "تمت إضافته إلى محفظتك",
    "wallet.withdrawnFrom": "تم سحبه من محفظتك",
    "wallet.depositError": "لم نتمكن من إتمام الإيداع",
    "wallet.withdrawError": "لم نتمكن من إتمام السحب",
    "wallet.confirmDeposit": "تأكيد الإيداع",
    "wallet.confirmWithdrawal": "تأكيد السحب",
    "wallet.processing": "جاري المعالجة...",
    "wallet.viewAll": "عرض جميع المعاملات",
    "wallet.noDescription": "لا يوجد وصف",
    "wallet.zainCash": "زين كاش",
    "wallet.alRafidain": "خدمات الرافدين QiServices",
    "wallet.fib": "FIB",
    "wallet.platformZainNumber": "رقم زين كاش الخاص بالمنصة",
    "wallet.transferToThisNumber": "حول المبلغ إلى هذا الرقم",
    "wallet.yourWalletNumber": "رقم محفظتك",
    "wallet.enterWalletNumber": "أدخل رقم محفظتك المستخدم للتحويل",
    "wallet.walletNumberHint": "أدخل رقم المحفظة التي استخدمتها لإرسال المبلغ",
    "wallet.platformRafidainAccount": "رقم حساب الرافدين الخاص بالمنصة",
    "wallet.transferToThisAccount": "حول المبلغ إلى هذا الحساب البنكي",
    "wallet.yourAccountNumber": "رقم حسابك",
    "wallet.enterAccountNumber": "أدخل رقم حسابك المستخدم للتحويل",
    "wallet.accountNumberHint": "أدخل رقم الحساب الذي استخدمته لإرسال المبلغ",
    "wallet.type": "النوع",
    "wallet.status": "الحالة",
    "wallet.date": "التاريخ",
    "wallet.sale": "بيع",
    "wallet.purchase": "شراء",
    "wallet.promotion": "ترويج",
    "wallet.completed": "مكتمل",
    "wallet.pending": "قيد الانتظار",
    "wallet.failed": "فشل",
    "wallet.feeNotice": "سيتم خصم رسوم",
    "wallet.depositFeeNotice": "سيتم تطبيق رسوم معالجة على هذا الإيداع",
    "wallet.withdrawFeeNotice": "سيتم تطبيق رسوم معالجة على هذا السحب",
    "wallet.depositAmount": "مبلغ الإيداع",
    "wallet.withdrawalAmount": "مبلغ السحب",
    "wallet.processingFee": "رسوم المعالجة (5%)",
    "wallet.youWillReceive": "سوف تحصل على",
    
    // Auth
    "auth.welcomeBack": "مرحباً بعودتك",
    "auth.createAccount": "إنشاء حساب",
    "auth.enterCredentials": "أدخل بيانات الدخول للوصول إلى حسابك",
    "auth.joinTiro": "انضم إلى تيرو وابدأ ببيع الخدمات الرقمية",
    "auth.fullName": "الاسم الكامل",
    "auth.email": "البريد الإلكتروني",
    "auth.username": "اسم المستخدم",
    "auth.password": "كلمة المرور",
    "auth.login": "تسجيل الدخول",
    "auth.dontHaveAccount": "ليس لديك حساب؟",
    "auth.signUp": "إنشاء حساب",
    "auth.alreadyHaveAccount": "لديك حساب بالفعل؟",
    "auth.loginSuccess": "تم تسجيل الدخول بنجاح!",
    "auth.welcomeTo": "مرحباً بعودتك إلى تيرو",
    "auth.accountCreated": "تم إنشاء الحساب!",
    "auth.welcomeToPlatform": "مرحباً بك في منصة تيرو",
    
    // My Products
    "myProducts.title": "منتجاتي",
    "myProducts.subtitle": "إدارة خدماتك وعروضك",
    "myProducts.addNewService": "إضافة خدمة جديدة",
    "myProducts.createService": "أنشئ خدمة جديدة لتقديمها في سوق تيرو",
    "myProducts.serviceTitle": "عنوان الخدمة",
    "myProducts.titlePlaceholder": "تصميم شعار احترافي",
    "myProducts.description": "الوصف",
    "myProducts.descriptionPlaceholder": "صف خدمتك بالتفصيل...",
    "myProducts.priceUSD": "السعر (دولار)",
    "myProducts.pricePlaceholder": "50.00",
    "myProducts.category": "الفئة",
    "myProducts.selectCategory": "اختر الفئة",
    "myProducts.accountDetails": "تفاصيل الحساب",
    "myProducts.accountUsername": "اسم مستخدم الحساب",
    "myProducts.accountPassword": "كلمة مرور الحساب",
    "myProducts.accountEmail": "بريد الحساب الإلكتروني",
    "myProducts.accountEmailPassword": "كلمة مرور البريد",
    "myProducts.subscriptionDuration": "مدة الاشتراك",
    "myProducts.selectDuration": "اختر المدة",
    "myProducts.1month": "شهر واحد",
    "myProducts.3months": "3 أشهر",
    "myProducts.6months": "6 أشهر",
    "myProducts.12months": "12 شهر",
    "myProducts.netflixDetails": "تفاصيل اشتراك نتفلكس",
    "myProducts.youtubeDetails": "تفاصيل حساب يوتيوب",
    "myProducts.spotifyDetails": "تفاصيل اشتراك سبوتفاي",
    "myProducts.telegramNumbersDetails": "تفاصيل رقم تليجرام",
    "myProducts.subscriptionsDetails": "تفاصيل حساب الاشتراك",
    "myProducts.subscriptionEmail": "بريد الحساب",
    "myProducts.subscriptionCode": "رمز / كلمة مرور الحساب",
    "myProducts.telegramPhoneNumber": "رقم الهاتف للبيع",
    "myProducts.telegramPhonePlaceholder": "",
    "myProducts.courseUrl": "رابط الكورس",
    "myProducts.courseUrlPlaceholder": "https://example.com/course",
    "myProducts.gameType": "اسم اللعبة",
    "myProducts.gameTypePlaceholder": "مثال: ببجي، فري فاير",
    "myProducts.usernamePlaceholder": "username123",
    "myProducts.passwordPlaceholder": "password",
    "myProducts.emailPlaceholder": "user@example.com",
    "myProducts.emailPasswordPlaceholder": "email password",
    "myProducts.saving": "جاري الحفظ...",
    "myProducts.updateService": "تحديث الخدمة",
    "myProducts.createServiceBtn": "إنشاء الخدمة",
    "myProducts.totalServices": "إجمالي الخدمات",
    "myProducts.totalViews": "إجمالي المشاهدات",
    "myProducts.totalSales": "إجمالي المبيعات",
    "myProducts.views": "مشاهدة",
    "myProducts.sales": "مبيعة",
    "myProducts.editService": "تعديل الخدمة",
    "myProducts.updateDetails": "حدّث تفاصيل خدمتك",
    "myProducts.deleteService": "حذف الخدمة",
    "myProducts.deleteConfirm": "هل أنت متأكد من حذف",
    "myProducts.deleteWarning": "لا يمكن التراجع عن هذا الإجراء.",
    "myProducts.deleting": "جاري الحذف...",
    "myProducts.noProducts": "لا توجد خدمات بعد",
    "myProducts.noProductsDescription": "أنشئ خدمتك الأولى للبدء بالبيع في تيرو",
    "myProducts.addFirstService": "أضف خدمتك الأولى",
    "myProducts.active": "نشط",
    "myProducts.inactive": "غير نشط",
    "myProducts.createSuccess": "تم إنشاء الخدمة بنجاح",
    "myProducts.updateSuccess": "تم تحديث الخدمة بنجاح",
    "myProducts.deleteSuccess": "تم حذف الخدمة بنجاح",
    "myProducts.verificationRequired": "التوثيق مطلوب",
    "myProducts.verificationMessage": "يمكن فقط للبائعين الموثقين نشر الخدمات على تيرو. يرجى التقدم بطلب توثيق الحساب للبدء في بيع خدماتك.",
    "myProducts.applyForVerification": "التقدم للحصول على التوثيق",
    
    // Promote
    "promote.title": "روّج لخدماتك",
    "promote.subtitle": "عزز ظهورك وتواصل مع المزيد من العملاء مع باقات الترويج",
    "promote.premiumSpotlight": "التركيز المميز",
    "promote.featuredPosition": "الموضع المميز",
    "promote.visibilityBoost": "تعزيز الظهور",
    "promote.top3Description": "احصل على أقصى ظهور مع الموضع المميز",
    "promote.top5Description": "تميز مع الموضع المميز",
    "promote.top10Description": "اجعل خدمتك ملحوظة",
    "promote.top3": "الأفضل 3",
    "promote.top5": "الأفضل 5",
    "promote.top10": "الأفضل 10",
    "promote.perPromotion": "/ترويج",
    "promote.selectPlan": "اختر الباقة",
    "promote.selectProduct": "اختر المنتج",
    "promote.chooseProduct": "اختر منتج للترويج",
    "promote.selectPromote": "اختر منتج للترويج مع",
    "promote.package": "باقة",
    "promote.promotionSummary": "ملخص الترويج",
    "promote.packageLabel": "الباقة",
    "promote.position": "الموضع",
    "promote.duration": "المدة",
    "promote.daysCount": "أيام",
    "promote.total": "الإجمالي",
    "promote.creating": "جاري الإنشاء...",
    "promote.startPromotion": "ابدأ الترويج",
    "promote.activePromotions": "الترويجات النشطة",
    "promote.activePromotionsDescription": "حملات الترويج الجارية حالياً",
    "promote.active": "نشط",
    "promote.day": "يوم",
    "promote.daysRemaining": "أيام متبقية",
    "promote.noPromotions": "لا توجد ترويجات نشطة",
    "promote.noPromotionsDescription": "ابدأ بترويج خدماتك لزيادة الظهور",
    "promote.activationSuccess": "تم تفعيل الترويج!",
    "promote.activationSuccessMessage": "تم إنشاء الترويج وهو نشط الآن.",
    "promote.activationFailed": "فشل الترويج",
    "promote.activationError": "فشل إنشاء الترويج",
    "promote.selectProductError": "الرجاء اختيار منتج للترويج",
    "promote.loginRequired": "يجب تسجيل الدخول لإنشاء ترويج",
    "promote.benefit1Top3": "مميز في أفضل 3 منتجات",
    "promote.benefit2Top3": "أقصى ظهور",
    "promote.benefit3Top3": "مُبرز بشارة ذهبية",
    "promote.benefit4Top3": "ترويج لمدة 3 أيام",
    "promote.benefit5Top3": "أولوية في نتائج البحث",
    "promote.benefit1Top5": "مميز في أفضل 5 منتجات",
    "promote.benefit2Top5": "ظهور عالي",
    "promote.benefit3Top5": "شارة مميزة",
    "promote.benefit4Top5": "ترويج لمدة يومين",
    "promote.benefit5Top5": "محسّن في البحث",
    "promote.benefit1Top10": "مميز في أفضل 10 منتجات",
    "promote.benefit2Top10": "ظهور جيد",
    "promote.benefit3Top10": "شارة ترويج",
    "promote.benefit4Top10": "ترويج لمدة يوم واحد",
    "promote.benefit5Top10": "تعزيز ترتيب البحث",
    
    // Profile
    "profile.title": "الملف الشخصي",
    "profile.editProfile": "تعديل الملف الشخصي",
    "profile.save": "حفظ",
    "profile.saving": "جاري الحفظ...",
    "profile.cancel": "إلغاء",
    "profile.personalInfo": "معلومات الملف الشخصي",
    "profile.personalInfoDescription": "معلوماتك الشخصية والسيرة الذاتية",
    "profile.fullName": "الاسم الكامل",
    "profile.username": "اسم المستخدم",
    "profile.email": "البريد الإلكتروني",
    "profile.bio": "النبذة الشخصية",
    "profile.performanceStats": "إحصائيات الأداء",
    "profile.performanceDescription": "إنجازاتك في تيرو",
    "profile.rating": "التقييم",
    "profile.reviews": "تقييم",
    "profile.totalSales": "إجمالي المبيعات",
    "profile.sellerRank": "ترتيب البائع",
    "profile.top": "الأفضل",
    "profile.accountStatus": "حالة الحساب",
    "profile.verification": "التحقق",
    "profile.verified": "موثّق",
    "profile.notVerified": "غير موثّق",
    "profile.memberSince": "عضو منذ",
    "profile.accountType": "نوع الحساب",
    "profile.seller": "بائع",
    "profile.quickActions": "إجراءات سريعة",
    "profile.changePassword": "تغيير كلمة المرور",
    "profile.notificationSettings": "إعدادات الإشعارات",
    
    // Not Found
    "notFound.title": "الصفحة غير موجودة",
    "notFound.message": "الصفحة التي تبحث عنها غير موجودة أو تم نقلها",
    "notFound.goHome": "الصفحة الرئيسية",
    "notFound.goBack": "رجوع",
    
    // Common
    "common.loading": "جاري التحميل...",
    "common.error": "خطأ",
    "common.success": "نجح",
    "common.cancel": "إلغاء",
    "common.confirm": "تأكيد",
    "common.save": "حفظ",
    "common.delete": "حذف",
    "common.edit": "تعديل",
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  // Fixed to Arabic only
  const language: Language = "ar";

  useEffect(() => {
    // Always set Arabic RTL direction
    document.documentElement.dir = "rtl";
    document.documentElement.lang = "ar";
    
    // Set Arabic font family
    document.documentElement.style.fontFamily = "'Tajawal', 'Inter', sans-serif";
  }, []);

  const setLanguage = (lang: Language) => {
    // Language switching disabled - Arabic only
    console.log("Language is locked to Arabic");
  };

  const t = (key: string): string => {
    return translations.ar[key as keyof typeof translations.ar] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
